# Generated by Django 4.2.1 on 2023-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joniApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimunial_image', models.ImageField(upload_to='testimonial/')),
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial_description', models.TextField(blank=True, max_length=500, null=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=60, null=True)),
                ('testimonial_post', models.CharField(blank=True, max_length=60, null=True)),
                ('testimonial_review', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
