# Generated by Django 4.2.1 on 2023-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joniApp', '0004_product_product_descriptions_product_product_legs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(to='joniApp.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_material',
            field=models.ManyToManyField(to='joniApp.material'),
        ),
    ]
