# Generated by Django 4.2.2 on 2023-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joniApp', '0006_category_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_comment', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
